### ISSUE TITLE
Can Kutty be used with Vite?

### ISSUE THREAD

**Issue by PabloC** [praveenjuge/kutty#29] opened 2021-01-27 21:51 UTC
I tried to use with this template (Vitesse), and for some reasons errors appear after adding Kutty in tailwind.config.js

Vitesse is an opinionated vite template.
https://github.com/antfu/vitesse

Tks!

**Comment by praveenjuge** [comment] 2021-01-29 04:20
Hey, thanks for showing me Vitesse, it's very nice.

When I add Kutty it was throwing errors for me too, Vitesse does some changes to tailwind variants in `tailwind.config.js` which Kutty depends upon. 

The problem is that using @apply inside a plugin is an anti pattern, the plugin breaks when the user changes the variants.

A temporary solution is to remove variants in `tailwind.config.js` file and remove the @apply usage in `main.postcss` file.

A permanent solution is for me to remove all @apply classes in the Kutty plugin, unfortunately this is a big refactor of the entire codebase.

I'm starting a new development cycle for Kutty on feb and this will be the first thing that I'm going to work on. Expect an update in a couple of days.

Thanks for raising an issue!

**Comment by praveenjuge** [comment] 2021-02-05 01:55
I have fixed the issues in the latest release [0.5.0](https://github.com/praveenjuge/kutty/releases/tag/0.5.0). 

There was also a little issue with vitesse which I have resolved in [this PR](https://github.com/antfu/vitesse/pull/47). So use the latest versions of Kutty and Vitesse and everything should be working good!

**Closed by praveenjuge** 2021-02-05 01:55 UTC
