### ISSUE TITLE
Error in tailwinds-intellisense

### ISSUE THREAD

**Issue by gapfranco** [praveenjuge/kutty#28] opened 2021-01-06 16:12 UTC
When we add the fluky plugin in a Phoenix application, the tailwindcss intelligence stops working VS Code.

Gives errors like: "tailwind CSS: <css input>:1:8: The `focus:ring` class does not exist. If you're sure that `focus:ring` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree."

The extension works, only the VS Code extension is affected.

**Comment by praveenjuge** [comment] 2021-01-07 01:45
I'll take a look 👍

**Comment by Destaq** [comment] 2021-01-28 17:21
Can confirm that this is still problematic. Perhaps a residual TailwindCSS 1 class @praveenjuge ? Do you have an estimate for when this will be fixed, it makes TailwindCSS work in VS Code much harder.

**Comment by Destaq** [comment] 2021-01-28 18:31
Here's the error in action: 
![image](https://user-images.githubusercontent.com/61620873/106182593-580eee80-619f-11eb-82cb-bf6cfec59cde.png)

**Comment by praveenjuge** [comment] 2021-01-29 03:19
Hey @Destaq and @gapfranco,
I can't seem to reproduce the issue, do you mind sharing your tailwind and intellisense versions? And your tailwind.config.js file too if possible.

**Comment by Destaq** [comment] 2021-01-29 08:45
@praveenjuge of course.

Contents of `tailwind.config.js`:
```js
module.exports = {
  purge: {
    enabled: false, // set to true for production
    content: ["./src/**/*.vue"],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        // for kutty - orange
        primary: {
          light: "#fab700",
          DEFAULT: "#ff8c00",
          dark: "#cc6300",
        },
        "pale-brown": "#e0d5b7",
        "pop-orange": "#ff8c00",
        "dark-gray": "#3d3d3d",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("kutty")],
};
```

Contents of `package.json`. **Note**: using Tailwind version 2.0, however - this is the postcss 7 compact version. Don't see why that would have an impact, however.
```json
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "build:css": "postcss ./src/tailwind.css -o ./src/tailwind_dist.css"
  },
  "dependencies": {
    "autoprefixer": "^9.8.6",
    "core-js": "^3.6.5",
    "kutty": "^0.4.1",
    "postcss": "^7.0.35",
    "postcss-cli": "^7.0.0",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2",
    "vue": "^3.0.0",
    "vue-router": "^4.0.3",
    "vuex": "^4.0.0-rc.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

Using the latest version of Tailwind CSS IntelliSense - 0.5.7.

**Comment by Destaq** [comment] 2021-01-29 08:46
Using the Postcss compat 7 due to backward compatibility issues - outlined on Tailwind's site [here](https://tailwindcss.com/docs/installation#install-tailwind-via-npm).

**Comment by Destaq** [comment] 2021-01-29 18:42
Fixed TailwindCSS Intellisense side in version 0.5.8!

**Comment by praveenjuge** [comment] 2021-01-30 03:02
That's nice! Thanks for raising an issue there!

**Closed by praveenjuge** 2021-01-30 03:02 UTC
